### ISSUE TITLE
cf unbind-service error

### ISSUE THREAD

**Issue by tanjoht** [mongodb/atlas-osb#27]
currently have version 0.5.0 of the broker deployed and seeing this on an instance that was renamed (and renamed back to the original). This instance may have been created prior to 0.5.0 where there were issues with renaming instances.

The error is:
Error: An unbind operation for the service binding between app mp-adapter and service instance mongodb-dso failed: Service broker error: cannot find plan for instance “instance id”: instance metadata has the wrong type map[string]interface {}

**Comment by jasonmimick** [comment]
Waiting on more info from customer

**Comment by alanlunspace** [comment]
Hi @jasonmimick ,

May I know what info are you looking for please?

**Comment by alanlunspace** [comment]
Hi @jasonmimick ,
May I have an update please?
Did I provide all info you need?
Thanks a lots.

**Comment by vasilevp** [comment]
Hi,
This happened because the service instance was created with an older (pre-v0.5) version of the Broker. It's not possible to use versions v5.0 and newer with these old instances as there was no backwards compatibility during these early stages of Broker development.
If you only have this one instance with such issue and are not hitting it with later versions of the Broker, please remove the broken instance by hand (delete from Atlas + `cf purge-service-instance`).

That being said, in the more recent releases we're able to provide better backwards compatibility since the whole design is getting a lot more stable.

Closing since this should not happen in latest versions.

**Comment by alanlunspace** [comment]
Hi @jasonmimick ,
We updated to v0.7.0 but still see this issue, please kindly advice.

**Comment by tanjoht** [comment]
there's actually 4 of the broker-state realm apps in the SEA preview org. 

We are waiting for @vasilevp to implement a fix to the broker and also provide a script to fix the duplicate realm apps. 

We can manually fix the instancesif needed.
