### ISSUE TITLE
a user is "defaulted" and assigned as project owner

### ISSUE THREAD

**Issue by tanjoht** [mongodb/atlas-osb#34]
When creating a Atlas service instance, a random user is added as a "project owner" for the project.

This may possibly be a bug/limitation with the create project API: POST https://cloud.mongodb.com/api/atlas/v1.0/groups

In the documentation it states:

IMPORTANT

To create a project using API Key credentials, you must specify an orgId. When you do, Atlas automatically selects the Owner of the specified organization with the earliest account creation date and time as the Project Owner for the newly created project.

Not sure if there is a way to change the account creation date for each org or to hard code a specific user to be set as the owner.

**Comment by tanjoht** [comment]
documentation at: https://docs.atlas.mongodb.com/reference/api/project-create-one/

**Comment by jasonmimick** [comment]
Since the atlas-osb does use the Atlas APIs to create Projects, and the API currently functions this way we aren't able to change this behavior.random
Since the user added as the project owner is in fact well-defined, I changed the title of this ticket slightly since it's not really a random user.

Since the user added is already an org owner so basically could access everything without this side-effect.
But, what are the implications of this behavior that are of concern for your organization? Let's see how to best address those.

**Comment by chomipi** [comment]
Couple reasons...

1. The user that is defaulted Project Owner has moved into a different part of the organization. We need to remove his full Org Owner rights and cannot do that until the default access is no longer provided, and he is removed as Project Owner from all projects.
2. Access reviews will point to the default Project Owner as the actual Project Owner, when in fact he has nothing to do with it.

**Comment by tanjoht** [comment]
Can we get an enhancement on the broker where we can hardcode a user into the plan? Upon project creation by the broker, they can assign this as the project owner. This way, we can specify a "service account" as project owner for all the projects.

A second solution is to have the API updated to not require a project owner (especially when the API token acts as the project owner).

**Comment by jasonmimick** [comment]
We are investigating a possible workaround where we can remove the 'auto-added' user via api calls, and will have an update soon. 
This would basically be your second approach, but we will do it in the broker with a couple extra api calls.
But, first we're checking make sure works and no edge cases.

**Comment by jasonmimick** [comment]
Update on investigation: :broken_heart: 

We updated the broker to attempt to remove the defaulted user from a newly created project, but this failed because the API does not allow that user to be deleted UNTIL the actually user who is calling create-service who is also added by the broker via API accepts the new invite.
Basically we can add users, but not delete that first "default" project owner until 1 invite gets accepted.

The broker is not going to be able to work around this documented functionality in Atlas, so we suggest using some additional tooling to help automate and keep these project and Atlas users properly managed.

For example, cluster administrators can use  `mongocli` to generate a report of all the projects a given user is in, in the event they leave the organization. Then you can automate removing them from those projects as well. 
(See: https://docs.mongodb.com/mongocli/master/reference/iam/iam-project-user-list/)
