### ISSUE TITLE
deleting service instance fails

### ISSUE THREAD

**Issue by tanjoht** [mongodb/atlas-osb#9]
When deleting a service instance using cf delete-service instance, the back end atlas has some issue and takes significantly longer than expected.

ie:

Deleting service atlas-osb-smoketest in org system / space atlas-osb as admin...
OK

Delete in progress. Use 'cf services' or 'cf service atlas-osb-smoketest' to check operation status.
atlas-osb-smoketest not deleted within 30 minutes

When looking at the project/cluster on atlas UI, the cluster is deleted by the project remains. The cf service instance is in a failed update status and cannot be deleted (only purged):

atlas-osb-smoketest already exists. deleting service instance
Deleting service atlas-osb-smoketest in org system / space atlas-osb as admin...
FAILED
Server error, status code: 502, error code: 10001, message: Service instance atlas-osb-smoketest: Service broker error: DELETE https://cloud.mongodb.com/api/atlas/v1.0/groups/xf/clusters/atlas-osb-smoketest: 404 (request "Not Found") No cluster named atlas-osb-smoketest exists in group x.
atlas-osb-smoketest not deleted within 30 minutes

**Comment by tanjoht** [comment]
this has occurred in a second environment

**Comment by jasonmimick** [comment]
Hi @tanjoht -

We did some investigation here and would need more details in order to fully diagnose this issue.
The only way to get a 404 back from Atlas on this scenario would be if somehow the cluster had already been delete or otherwise manipulated directly through Atlas (like someone deleted the cluster in the Atlas UI, maybe). 
We need
* logs - (cf logs atlas-osb)
* exact steps to reproduce this issue
* Atlas orgs 
in order to proceed with our investigation.

Thanks

**Comment by leo-ri** [comment]
Likely it was related to the update command, which was previously fixed, and the latest release contains a rename fix as well.

**Comment by jasonmimick** [comment]
Closing this pending testing new release, please reopen if the issue still occurs.
